@echo off
setlocal enabledelayedexpansion
title Footprints Chrome Profile Manager

:: --- CONFIGURATION ---
:: Permanent storage location
set "InstallDir=C:\ProgramData\Footprints_Scripts"
set "ScriptFile=%InstallDir%\WipeChrome.ps1"

:: Task Names (New and Old)
set "TaskName=FIS_DeleteChromeProfiles"
set "LegacyTaskName=DeleteChromeProfilesTask"

:menu
:: Set window size slightly larger to prevent wrapping glitches
mode con: cols=85 lines=25
cls
color 0B

echo.
echo  ================================================================================
echo.
echo      #######  #######  #######  #######  ######   ######   ###  #   #  #######
echo      #        #     #  #     #     #     #     #  #     #   #   ##  #     #
echo      #####    #     #  #     #     #     ######   ######    #   # # #     #
echo      #        #     #  #     #     #     #        #   #     #   #  ##     #
echo      #        #######  #######     #     #        #    #   ###  #   #     #
echo.
echo                          C H R O M E   M A N A G E R
echo  ================================================================================
echo.
echo    [1] ENABLE Auto-Wipe
echo        (Deletes Chrome Data on Every Restart)
echo.
echo    [2] DISABLE / RESET 
echo        (Removes restrictions & Fixes legacy versions)
echo.
echo    [Q] Quit
echo.
echo  ================================================================================
echo.

set /p choice=Select an option: 

if /i "%choice%"=="1" goto install
if /i "%choice%"=="2" goto uninstall
if /i "%choice%"=="Q" goto quit

goto menu

:: ---------------------------------------------------------
:: OPTION 1: INSTALL
:: ---------------------------------------------------------
:install
cls
echo.
echo [!] Initializing Installation...

:: 1. Create directory
if not exist "%InstallDir%" (
    mkdir "%InstallDir%" >nul 2>&1
)

:: 2. Generate PowerShell Payload
echo Creating PowerShell payload...
(
echo # PowerShell script to delete Chrome user profiles
echo # Generated by Footprints IT Toolbox
echo.
echo $profiles = Get-WmiObject Win32_UserProfile ^| Where-Object { $_.Special -eq $false }
echo foreach ^($profile in $profiles^) {
echo     $chromePath = Join-Path $profile.LocalPath 'AppData\Local\Google\Chrome\User Data'
echo     if ^(Test-Path $chromePath^) {
echo         try {
echo             Remove-Item -Path $chromePath -Recurse -Force -ErrorAction SilentlyContinue
echo             Write-Host "Deleted: $($profile.LocalPath)"
echo         } catch { }
echo     }
echo }
) > "%ScriptFile%"

:: 3. Create Task (And remove old legacy task if it exists)
schtasks /delete /tn "%LegacyTaskName%" /F >nul 2>&1
schtasks /create /tn "%TaskName%" /tr "powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File \"%ScriptFile%\"" /sc onstart /ru SYSTEM /F >nul 2>&1

if %errorlevel%==0 (
    echo.
    echo [OK] SUCCESS! 
    echo Chrome profiles will be wiped on every restart.
) else (
    echo.
    echo [X] ERROR: Run as Administrator.
)

echo.
pause
goto menu

:: ---------------------------------------------------------
:: OPTION 2: UNINSTALL / RESET
:: ---------------------------------------------------------
:uninstall
cls
echo.
echo [!] Resetting Configuration...

:: 1. Delete the NEW Task
echo Removing Current Task...
schtasks /delete /tn "%TaskName%" /F >nul 2>&1

:: 2. Delete the OLD Legacy Task (The Ghost!)
echo Removing Legacy Task...
schtasks /delete /tn "%LegacyTaskName%" /F >nul 2>&1

:: 3. Delete Files
echo Removing Script Files...
if exist "%ScriptFile%" (
    del /f /q "%ScriptFile%" >nul 2>&1
)
rmdir "%InstallDir%" >nul 2>&1

echo.
echo [OK] SUCCESS!
echo All Chrome restrictions (including old versions) have been removed.
echo.
pause
goto menu

:quit
exit
