@echo off
setlocal enabledelayedexpansion
title Footprints Chrome Profile Manager

:: --- CONFIGURATION ---
:: We store the script in ProgramData so it doesn't get deleted by Windows Cleanup
set "InstallDir=C:\ProgramData\Footprints_Scripts"
set "ScriptFile=%InstallDir%\WipeChrome.ps1"
set "TaskName=FIS_DeleteChromeProfiles"

:menu
cls
mode con: cols=80 lines=20
color 0A

echo.
echo ==============================================================================
echo                      CHROME PROFILE MANAGER (AUTO-WIPE)
echo ==============================================================================
echo.
echo    [1] ENABLE Auto-Wipe (Deletes Chrome Data on Every Restart)
echo    [2] DISABLE / RESET (Remove Task and Stop Deleting)
echo    [Q] Quit
echo.
echo ==============================================================================
echo.

set /p choice=Select an option: 

if /i "%choice%"=="1" goto install
if /i "%choice%"=="2" goto uninstall
if /i "%choice%"=="Q" goto quit

goto menu

:: ---------------------------------------------------------
:: OPTION 1: INSTALL
:: ---------------------------------------------------------
:install
cls
echo.
echo [!] Initializing Installation...

:: 1. Create the permanent directory if it doesn't exist
if not exist "%InstallDir%" (
    mkdir "%InstallDir%" >nul 2>&1
)

:: 2. Generate the PowerShell Script in the permanent folder
echo Creating PowerShell payload...
(
echo # PowerShell script to delete Chrome user profiles for all users
echo # Generated by Footprints IT Toolbox
echo.
echo $profiles = Get-WmiObject Win32_UserProfile ^| Where-Object { $_.Special -eq $false }
echo foreach ^($profile in $profiles^) {
echo     $chromePath = Join-Path $profile.LocalPath 'AppData\Local\Google\Chrome\User Data'
echo     if ^(Test-Path $chromePath^) {
echo         try {
echo             Remove-Item -Path $chromePath -Recurse -Force -ErrorAction SilentlyContinue
echo             Write-Host "Deleted: $($profile.LocalPath)"
echo         } catch {
echo             Write-Host "Could not delete locked files."
echo         }
echo     }
echo }
) > "%ScriptFile%"

:: 3. Create the Scheduled Task
echo Creating Scheduled Task...
:: /F forces creation (overwrites if exists)
schtasks /create /tn "%TaskName%" /tr "powershell.exe -ExecutionPolicy Bypass -WindowStyle Hidden -File \"%ScriptFile%\"" /sc onstart /ru SYSTEM /F >nul 2>&1

if %errorlevel%==0 (
    echo.
    echo [OK] SUCCESS! 
    echo Chrome profiles will now be wiped every time this computer turns on.
) else (
    echo.
    echo [X] ERROR: Could not create task. Run as Administrator.
)

echo.
pause
goto menu

:: ---------------------------------------------------------
:: OPTION 2: UNINSTALL / RESET
:: ---------------------------------------------------------
:uninstall
cls
echo.
echo [!] Resetting Configuration...

:: 1. Delete the Scheduled Task
echo Removing Scheduled Task...
schtasks /delete /tn "%TaskName%" /F >nul 2>&1

:: 2. Delete the PowerShell Script
echo Removing Script Files...
if exist "%ScriptFile%" (
    del /f /q "%ScriptFile%" >nul 2>&1
)

:: 3. Remove the folder if it is empty
rmdir "%InstallDir%" >nul 2>&1

echo.
echo [OK] SUCCESS!
echo The auto-wipe feature has been disabled. Chrome is back to normal.
echo.
pause
goto menu

:quit
exit
