@echo off
setlocal enabledelayedexpansion

:: --- CONFIGURATION ---
:: We use ProgramData (All Users) so this applies to Students & Teachers
set "StartupDir=C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp"
set "ScriptFile=%StartupDir%\ForceDisplayReset.bat"

:menu
:: Standardize Window Size and Color (White on Black)
mode con: cols=85 lines=25
color 07
cls

echo.
echo ==============================================================================
echo                         DISPLAY CONTROL MANAGER
echo ==============================================================================
echo.
echo    [1] ENABLE Auto-Reset
echo        (Forces 'Duplicate' & Turns OFF Night Light after Logon)
echo.
echo    [2] DISABLE / RESET 
echo        (Removes the startup script)
echo.
echo    [Q] Exit
echo.
echo ==============================================================================
echo.

:: Check Status
if exist "%ScriptFile%" (
    echo    STATUS: [ ENABLED ] - Display will reset on every login.
) else (
    echo    STATUS: [ DISABLED ] - No active restrictions.
)
echo.

set /p choice=Select an option: 

if "%choice%"=="1" goto enable
if "%choice%"=="2" goto disable
if /i "%choice%"=="Q" goto exit

goto menu

:: ---------------------------------------------------------
:: OPTION 1: ENABLE (Duplicate + Night Light Off)
:: ---------------------------------------------------------
:enable
cls
echo.
echo [!] Enabling Display Auto-Reset...

:: Create the startup script
(
echo @echo off
echo :: Generated by Footprints IT Toolbox
echo :: 1. Wait for Graphics Drivers to load
echo timeout /t 5 /nobreak ^>nul
echo.
echo :: 2. Force Night Light OFF ^(Delete Registry Config^)
echo reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\CloudStore\Store\DefaultAccount\Cloud\default$windows.data.bluelightreduction" /f ^>nul 2^>^&1
echo.
echo :: 3. Force Duplicate Mode ^(First Attempt^)
echo DisplaySwitch.exe /clone
echo timeout /t 2 /nobreak ^>nul
echo.
echo :: 4. Force Duplicate Mode ^(Second Attempt to ensure stickiness^)
echo DisplaySwitch.exe /clone
echo exit
) > "%ScriptFile%"

echo.
echo [OK] SUCCESS!
echo      A startup task has been created for ALL USERS.
echo      1. Monitors will force 'Duplicate' mode.
echo      2. Night Light (Yellow Screen) will be forced OFF.
echo.
pause
goto menu

:: ---------------------------------------------------------
:: OPTION 2: DISABLE
:: ---------------------------------------------------------
:disable
cls
echo.
echo [!] Disabling Display Auto-Reset...

if exist "%ScriptFile%" (
    del /f /q "%ScriptFile%" >nul 2>&1
    echo.
    echo [OK] SUCCESS!
    echo      Startup script removed. Display settings will now persist.
) else (
    echo.
    echo [INFO] It was already disabled.
)

echo.
pause
goto menu

:exit
color 07
exit